import 'dart:convert';
import 'dart:ui';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier(String? langCode, String? countryCode)
      : super(_initLocale(langCode, countryCode));

  static Locale _initLocale(String? langCode, String? countryCode) {
    if (langCode != null) {
      return Locale(langCode, countryCode);
    }
    // 探测系统语言：如果是中文环境则默认为 zh_CN，否则默认为 en_US
    final systemLocale = PlatformDispatcher.instance.locale;
    if (systemLocale.languageCode.contains('zh')) {
      return const Locale('zh', 'CN');
    }
    return const Locale('en', 'US');
  }

  Future<void> setLocale(Locale locale) async {
    state = locale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
    await prefs.setString('country_code', locale.countryCode ?? '');
  }
}

final localizationProvider =
    StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  // This will be overridden in main.dart
  return LocaleNotifier(null, null);
});

class S {
  final Locale locale;

  S(this.locale);

  static const LocalizationsDelegate<S> delegate = _SDelegate();

  static final _localizedValues = {
    'zh': {
      'sub_settings': '订阅设置',
      'nodes_manage': '节点管理',
      'advanced_config': '高级配置',
      'control_panel': '控制面板',
      'all_logs': '全部日志',
      'realtime_logs': '实时日志',
      'download': '下载',
      'upload': '上传',
      'global_mode': '全局模式',
      'rule_mode': '规则模式',
      'direct_mode': '直连模式',
      'logs_copied': '日志已复制到剪贴板',
      'no_logs_found': '暂无日志记录',
      'logs_help_desc': '启动代理后将在此显示运行日志',
      'failure_diagnosis': '连接失败诊断',
      'diagnostic_suggestion': '💡 建议：如果以上操作无法解决问题，请尝试切换其他节点或检查网络连接。',
      'got_it': '我知道了',
      'app_subtitle': 'The Next Gen Proxy Client',
      'app_version': 'Version 1.0.32 • Build 35',
      'app_status_stable': 'v1.0.0 Stable',
      'realtime_traffic_chart': '实时流量图表',
      'traffic_and_mode': '流量统计与模式控制',
      'traffic_and_mode_help': '显示实时上传下载速度以及总流量。你可以通过上方的模式开关快速切换全局、规则或直连模式。',
      'tunnel_details': '隧道详情',
      'tunnel_details_help':
          '在这里你可以快速切换当前连接的服务器节点、调整分流策略，以及一键开启/关闭 Windows 系统代理接管。\n\n提示：当前测速采用 HTTPS 真连接握手测试，反映实际访问网页的响应速度。',
      'net_recovering': '正在检查网络连通性...',
      'net_recovered': '网络已恢复，正在尝试自动重连',
      'wintun_missing': '缺少核心虚拟网卡驱动 wintun.dll，请确保程序目录完整或重新安装。',
      'file_path': '文件路径',
      'enter_file_path': '请输入文件路径',
      'enter_sub_link': '请输入订阅链接',
      'invalid_sub_link': '请输入有效的 http:// 或 https:// 链接',
      'auto_reload_file': '定期重新读取文件内容',
      'update_interval_hours': '更新间隔 (小时): ',
      'import_from_clipboard_desc': '导入已复制的链接或订阅',
      'import_from_file_desc': '支持 JSON 或链接列表文件',
      'no_nodes_found': '暂无可用节点',
      'edit_node_label': '编辑节点',
      'test_latency': '测试延迟',
      'copy_link_label': '复制链接',
      'share_qr': '二维码分享',
      'export_config_label': '导出完整配置',
      'physical_destroy': '物理销毁',
      'link_copied_success': '链接已复制到剪贴板',
      'confirm_delete': '确认删除',
      'delete_node_confirm': '确定要删除节点 "{name}" 吗？',
      'multi_select': '多选模式',
      'delete_node_label': '删除节点',
      'batch_export_success': '已将 {count} 个节点导出到剪贴板',
      'close': '关闭',
      'manual_add_ss': '手动添加 Shadowsocks',
      'strong_deduplicate': '节点强力去重',
      'nodes_cleanup': '节点大扫除',
      'clear_timeout': '清除超时节点',
      'clear_timeout_success': '已物理清除 {count} 个失效节点',
      'deduplicate_success': '已成功合并 {count} 个重复节点',
      'test_group_latency': '测试该组延迟',
      'test_all_speed': '全部测速',
      'search_nodes': '搜索节点...',
      'selected_count': '已选择 {count}',
      'stop_speed_test': '停止测速',
      'import_clipboard': '导入剪贴板链接',
      'import_from_file': '从文件导入',
      'sort_latency': '按延迟排序',
      'sort_name': '按名称排序',
      'manual_add_vmess': '手动添加 VMess',
      'manual_add_vless': '手动添加 VLESS',
      'manual_add_trojan': '手动添加 Trojan',
      'manual_add_shadowsocks': '手动添加 Shadowsocks',
      'manual_add_socks': '手动添加 SOCKS',
      'manual_add_hysteria2': '手动添加 Hysteria2',
      'manual_add_tuic': '手动添加 TUIC',
      'manual_add_wireguard': '手动添加 WireGuard',
      'auto_deduplicate': '自动去重',
      'auto_select_best': '自动优选节点',
      'auto_selecting': '正在自动优选最优节点...',
      'auto_select_done': '已为您切换至当前最快节点',
      'auto_select_failed': '自动优选失败，请检查网络',
      'speed_test_progress': '测速进度',
      'nodes_count': '{count} 个节点',
      'manual_import': '手动导入',
      'sub_update_failed': '订阅 "{name}" 更新失败: {error}',
      'sub_update_success': '订阅 "{name}" 更新成功',
      'update_all': '全部更新',
      'manual_input': '手动输入',
      'no_subs_found': '暂无订阅内容',
      'click_add_sub': '点击右上角按钮添加订阅链接',
      'clipboard_empty': '剪贴板为空',
      'no_valid_sub_link': '剪贴板中没有有效的订阅链接 (需以 http 开头)',
      'edit_sub_label': '编辑订阅',
      'close_auto_update': '关闭自动更新',
      'open_auto_update': '开启自动更新',
      'copy_sub_link': '复制订阅链接',
      'sub_link_copied': '订阅链接已复制到剪贴板',
      'delete_sub_label': '删除订阅',
      'enter_sub_name_hint': '请输入订阅名称',
      'delete_sub_confirm': '确定要删除订阅 "{name}" 吗？相关的节点也将被移除。',
      'enter_at_least_one': '请至少填写一个过滤条件',
      'operation_failed_need_admin': '操作失败，可能需要管理员权限',
      'search_apps_hint': '搜索应用名称...',
      'exempt_all': '全部豁免',
      'clear_all': '全部清除',
      'scanned_apps_count': '已扫描 {count} 个应用',
      'no_apps_found': '未发现匹配的应用',
      'uwp_exemption_warning': '注意：修改豁免列表后，相关应用可能需要重启才能生效。',
      'remote_dns_preset': '预设远程 DNS',
      'domestic_dns_preset': '预设国内 DNS',
      'fake_dns': 'Fake DNS',
      'enable_fake_dns': '启用 Fake DNS',
      'fake_dns_desc': '大幅提升域名解析速度并减少延迟',
      'remote_dns_desc': '建议使用加密 DNS (DoH/DoT) 以防止污染',
      'enable_ipv6': '启用 IPv6',
      'enable_ipv6_desc': '是否解析并返回 IPv6 地址',
      'domestic_dns': '国内 DNS',
      'domestic_dns_desc': '用于直连流量的域名解析',
      'local_dns': '本地 DNS 服务',
      'enable_local_dns': '开启本地 DNS',
      'enable_local_dns_desc': '在本地建立 DNS 监听服务',
      'local_dns_port': '监听端口',
      'local_dns_port_desc': '默认 10853',
      'dns_hosts': 'DNS 静态映射 (Hosts)',
      'dns_hosts_desc': '自定义域名到 IP 的静态映射',
      'preset': '预设',
      'connecting_to_network': '正在建立网络连接...',
      'encrypting_tunnel': '正在加密VPN隧道',
      'vpn_running': 'VPN服务运行中',
      'vpn_stopped': '未启用服务',
      'vpn_connected_success': '已成功启用加密隧道连接节点',
      'initializing_protocol': '正在初始化加密协议',
      'click_switch_to_start': '点击右侧开关开启加速',
      'select_node_first': '请先选择一个节点',
      'duration': '时长',
      'protocol': '协议',
      'unknown': '未知',
      'status': '状态',
      'stable': '稳定',
      'standby': '待命',
      'no_node_selected': '未选择节点',
      'click_to_change_routing': '点击切换路由策略',
      'connection_failed': '连接失败',
      'connection_failed_desc': '节点连接失败，可能是配置不兼容或节点已失效，请尝试更换节点。',
      'hide_details': '隐藏详情',
      'view_error_details': '查看错误详情',
      'error_log_copied': '错误日志已复制到剪贴板',
      'copy_log': '复制日志',
      'kernel_start_failed': '内核启动失败：{error}',
      'port_in_use':
          '端口被占用：Lightning 需要的本地端口（如 10808）已被其他程序霸占。请检查是否开启了其他代理软件（如 Clash、v2rayN 等），关闭后再试。',
      'tun_elevation_failed':
          '权限不足：TUN 虚拟网卡模式需要管理员权限。请右键点击 Lightning 快捷方式，选择「以管理员身份运行」。',
      'start_timeout': '启动超时：内核响应超时，请检查节点配置是否有效或重启软件。',
      'show_main_window': '显示主界面',
      'take_over_system_proxy': '接管系统代理',
      'routing_mode': '路由模式',
      'mode_rule_label': '规则模式',
      'mode_global_label': '全局模式',
      'mode_direct_label': '直连模式',
      'disconnect_vpn': '断开连接',
      'connect_vpn': '开启加速',
      'exit_app': '退出程序',
      'more_actions': '更多操作',
      'switching_node': '正在切换节点...',
      'stopping_vpn': '正在停止 VPN...',
      'auto_reset_tun': '已自动重置 TUN 模式开关',
      'preparing_resources': '正在准备资源文件...',
      'submitting_config': '正在下发配置到内核并请求 VPN 权限...',
      'net_disconnected': '[Connectivity] 网络已断开',
      'sub_sync_start': '订阅 [{name}] 达到更新间隔，开始自动同步...',
      'mode_changed_restarting': '检测到运行模式变更，正在更新内核配置...',
      'rules_changed_restarting': '检测到路由规则变更，正在更新内核配置...',
      'auto_reconnect_triggered': '[Tracer] ⚠️ 触发自动重连机制',
      'high_freq_jitter_blocked': '[Tracer] 🛡️ 拦截到极高频网络抖动，放弃本次重连',
      'duplicate_restart_ignored': '[Restart] 检测到重复重启请求，已忽略',
      'vpn_disconnected_by_cleanup': '[Tracer] 🔌 VPN 状态被修改为断开，触发者: 重连前置清理',
      'vpn_disconnected_by_user': '[Tracer] 🔌 VPN 状态被修改为断开，触发者: 用户主动停止',
      'vpn_disconnected_by_kernel': '[Tracer] 🔌 VPN 状态被修改为断开，触发者: 异常终止或内核退出',
      'vpn_connected_success_log': '[Flutter] VPN 连接成功!',
      'vpn_disconnected_log': '[Flutter] VPN 已断开',
      'kernel_error_log': '[Flutter] 内核错误: {error}',
      'preparing_node_log': '准备连接节点: {name}',
      'start_vpn_failed_log': '启动 VPN 失败: {error}',
      'stop_vpn_failed_log': '断开 VPN 失败: {error}',
      'driver_missing_error':
          '🛡️ 驱动缺失：缺少核心虚拟网卡驱动 wintun.dll，请确保程序目录完整或以管理员身份重新运行软件。',
      'tun_components_lost': '检测到 TUN 模式核心组件丢失，无法启动加密隧道。',
      'tray_tooltip_connected': 'Lightning VPN (已连接)',
      'tray_tooltip_disconnected': 'Lightning VPN',
      'tray_tooltip_connecting': 'Lightning VPN (连接中...)',
      'confirm_sub_info': '确认订阅信息',
      'add_subscription': '添加订阅',
      'sub_name': '订阅名称',
      'give_sub_name': '给订阅起个名字',
      'enter_sub_name': '请输入订阅名称',
      'auto_update': '自动更新',
      'sync_cloud_nodes': '定期同步云端节点',
      'routing_rules': '路由规则',
      'no_custom_rules': '暂无自定义规则',
      'click_add_rule': '点击右上角按钮添加分流规则',
      'rule_options': '规则选项',
      'delete_rule': '删除规则',
      'add_rule': '添加规则',
      'domain_comma': '域名 (逗号分隔)',
      'domain_label': '域名',
      'ip_comma': 'IP (逗号分隔)',
      'ip_label': 'IP',
      'port_comma': '端口 (逗号分隔)',
      'port_label': '端口',
      'protocol_comma': '协议 (逗号分隔)',
      'protocol_label': '协议',
      'network_label': '网络',
      'action': '动作',
      'direct_action': '直连 (Direct)',
      'proxy_action': '代理 (Proxy)',
      'block_action': '阻断 (Block)',
      'enter_at_least_one': '请输入至少一个过滤条件',
      'app_split': '应用分流',
      'bypass_apps_desc': '绕过所选应用 (黑名单)',
      'proxy_apps_desc': '代理所选应用 (白名单)',
      'search_installed_apps': '搜索已安装应用...',
      'kernel_info': '内核信息',
      'kernel_info_help':
          '功能：显示底层代理引擎的相关信息。\n\n详情：Lightning 采用 Xray-core 作为核心，支持多种协议并具备极高的转发性能。',
      'log_level': '日志级别',
      'log_level_help':
          '功能：控制代理内核输出日志的详细程度。\n\n开启：高级别（DEBUG/INFO）日志有助于排查连接问题，但会占用更多系统资源；低级别（ERROR/NONE）则能保持系统简洁。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'mux_title': 'Mux 多路复用',
      'mux_desc': '通过单条 TCP 连接并行传输多个数据流，显著降低延迟并提升握手效率',
      'mux_enabled_help':
          '功能：在单个 TCP 连接中并发传输多个子流。\n\n开启：显著降低频繁访问小文件时的 TCP 握手延迟（如网页加载），提升响应速度。\n\n关闭：对于单个大文件下载更稳定，在某些运营商网络下带宽上限更高。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'fragment_title': '开启 Fragment (防 SNI 阻断)',
      'fragment_desc': '将 TLS 握手包进行分片发送，有效绕过针对 SNI 域名的封锁和阻断',
      'fragment_help':
          'Fragment 模式可以显著提高在严苛网络环境下的连通率，尤其是在应对某些地区对特定域名的精准封锁时。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'system_proxy_title': '自动开启系统代理',
      'system_proxy_desc': '启动核心后自动修改 Windows 注册表劫持流量',
      'system_proxy_help':
          '功能：自动配置 Windows 系统代理设置。\n\n开启：大部分浏览器和系统流量将自动走代理，无需手动配置。\n\n关闭：需要手动在各个应用中设置代理。',
      'sniffing_title': '流量嗅探 (Sniffing)',
      'sniffing_desc': '识别加密流量中的真实域名以实现更精准的分流',
      'sniffing_help':
          '流量嗅探可以从 TLS/HTTP 握手包中提取目标域名。这对于处理基于 IP 的规则或规避 DNS 污染非常有效。',
      'domain_strategy_title': '域名解析策略',
      'domain_strategy_help':
          'AsIs: 直接使用域名，由服务器解析。\n\nIPIfNonMatch: 如果域名没有匹配规则，则解析为 IP 后再次匹配。\n\nIPOnDemand: 只要匹配到基于 IP 的规则，就立即解析域名。',
      'tun_stack_title': 'TUN 协议栈',
      'tun_stack_help':
          'gVisor: 用户态协议栈，兼容性最好且最安全，推荐使用。\n\nSystem: 使用 Windows 系统协议栈，性能较高但在某些环境下不稳定。\n\nMixed: 混合模式。',
      'clean_proxy_on_exit_title': '退出时清理代理',
      'clean_proxy_on_exit_desc': '关闭软件时自动还原 Windows 系统代理设置',
      'clean_proxy_on_exit_help':
          '开启后，当您彻底退出 Lightning 时，系统会自动清理注册表中的代理配置，防止因软件意外关闭导致无法正常上网。',
      'hide_to_tray_title': '隐藏到托盘',
      'hide_to_tray_desc': '关闭窗口时隐藏到系统托盘，不退出程序',
      'hide_to_tray_help': '功能：在关闭主窗口时保持程序在后台运行。\n\n你可以通过系统托盘图标恢复窗口或退出程序。',
      'rules_manage': '规则管理',
      'rules_db_manage': '规则库管理',
      'sync_geodata': '同步最新路由规则 (GeoData)',
      'sync_geodata_desc': '从 GitHub 同步最新的 geoip.dat 和 geosite.dat',
      'updating_geodata': '正在下载: {progress}%',
      'update_geodata_success': '✨ 路由规则库已更新至最新版',
      'update_geodata_failed': '❌ 更新失败: {error}',
      'disconnect_before_update': '⚠️ 请先断开连接再更新路由库',
      'ui_display': '界面显示',
      'appearance': '外观',
      'dark_mode': '深色模式',
      'light_mode': '浅色模式',
      'language': '语言',
      'conn_automation': '连接自动化',
      'uwp_exemption_title': 'UWP 环回豁免工具',
      'uwp_exemption_desc': '解决 Windows 应用商店程序无法联网的问题',
      'inbound_ports_title': '入站端口设置',
      'inbound_ports_desc': 'Socks: {socks} | HTTP: {http}',
      'backup_restore_desc': '导出当前配置到剪贴板或从剪贴板恢复',
      'rules_manage_desc': '自定义域名与 IP 路由规则',
      'bypass_local_desc': '绕过局域网地址 (如 192.168.x.x)',
      'allow_lan_desc': '允许局域网内的其他设备通过本机上网',
      'current_mode': '当前模式',
      'app_split_desc': '选择需要/不需要代理的应用',
      'rules_manage_help': '功能：管理域名和 IP 地址的自定义路由规则。\n\n你可以定义哪些流量走代理、直连或拦截。',
      'uwp_exemption_help':
          '功能：修复 Windows UWP 应用（如微软商店、Edge 等）因“回环限制”无法通过本地代理上网的问题。',
      'dns_settings_help':
          '功能：配置 DNS 解析策略和服务器。\n\n包含海外远程 DNS、国内 DNS 以及防污染的 Fake DNS。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'backup_restore': '备份与恢复',
      'backup_restore_help': '功能：将当前的节点和设置导出到剪贴板，或从之前导出的备份字符串中恢复。',
      'about': '关于',
      'about_desc': '查看软件信息',
      'about_help': 'Lightning 是一款高性能网络代理客户端。此页面显示了软件版本、内核信息及开发者详情。',
      'dns_settings': 'DNS 设置',
      'routing_strategy': '路由策略',
      'routing_strategy_help':
          '全局模式：所有网络请求全部经过代理，适合需要全时隐藏 IP 的场景，但访问国内网站可能变慢。\n\n规则模式：基于规则列表智能判断，国内网站直连，海外网站走代理，推荐使用。\n\n直连模式：不使用代理，直接连接互联网。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'bypass_local': '绕过局域网',
      'bypass_local_help':
          '功能：识别 192.168.x.x 等局域网地址。\n\n开启：访问家里的路由器、NAS、打印机时直接连接，不走代理，速度最快且互访正常。\n\n关闭：局域网流量也可能被重定向到代理服务器，导致无法访问本地设备。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'tcp_congestion': 'TCP 拥塞控制',
      'tcp_congestion_help':
          'BBR：Google 开发的新型拥塞算法，特别适合高丢包、长距离的跨境网络，能榨干带宽性能。\n\nCubic/Reno：经典的 TCP 算法，兼容性好，在低丢包的稳定网络下表现良好。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'allow_lan': '允许局域网连接',
      'allow_lan_help':
          '功能：将本机的代理网络共享给局域网内的其他设备（手机、主机、其他电脑）使用。\n\n使用说明：\n1. 确保本机防火墙已允许 Lightning 通过，且设备处于同一局域网。\n2. 记下本机的局域网 IP（{ip}）和 HTTP 代理端口（{port}）。\n3. 在其他设备的网络设置中手动配置代理：\n   - 服务器/主机名：{ip}\n   - 端口：{port}\n\n注意：开启后本机将作为代理网关运行。此设置需重启连接生效。',
      'lan_ip_title': '局域网 IP 地址',
      'lan_port_title': '代理端口',
      'copy_address': '复制地址',
      'inbound_ports_help':
          '功能：设置本地 Socks5 和 HTTP 代理服务的监听端口。\n\n开启：本机其他应用或局域网内其他设备可以通过手动设置这些端口来连接代理。\n\n关闭：将不开放本地入站端口，无法进行手动代理配置。\n\n注意：此设置需要重启 VPN 连接后才能生效。',
      'auto_start_help': '系统启动时自动运行 Lightning',
      'auto_start_tip':
          '功能：开启后，Lightning 将在 Windows 启动时自动加载。\n\n配合“静默启动”使用效果更佳。',
      'sync_geodata_help':
          '功能：从官方源更新路由数据库（geoip.dat / geosite.dat）。\n\n注意：更新路由库需要断开 VPN 连接。',
      'tun_mode_help':
          '功能：通过虚拟网卡（Wintun）接管系统全局流量。\n\n开启：所有软件（包括不支持代理设置的软件）都将自动通过代理上网。\n\n要求：需要管理员权限，且会安装 Wintun 驱动。',
      'appearance_help': '功能：切换应用的主题风格（明亮或深色模式）。',
      'language_help': '功能：切换应用显示的界面语言（中文或英文）。',
      'auto_start': '开机自启',
      'auto_start_help': '系统启动时自动运行 Lightning',
      'keep_alive': '持续运行',
      'keep_alive_help': '功能：防止系统杀掉后台进程。',
      'auto_reconnect': '自动重连',
      'auto_reconnect_help': '功能：网络中断或切换时自动尝试重新连接。',
      'hotkey_title': '主界面显隐快捷键',
      'hotkey_help':
          '功能：设置全局快捷键，随时随地快速唤醒或隐藏 Lightning 主界面。\n\n格式：支持 Alt, Ctrl, Shift 与字母组合（如 Alt+Q）。',
      'hotkey_input_label': '按键组合',
      'hotkey_format_hint': '格式示例：Alt+Q, Ctrl+Shift+S',
      'show_traffic': '显示网速',
      'show_traffic_help': '功能：在状态栏或悬浮窗显示实时上传下载速度。',
      'route_splitting': '路由与分流',
      'protocol_kernel': '协议与内核',
      'adv_network': '高级网络设置',
      'remote_dns': '远程 DNS',
      'about_title': '关于 Lightning',
      'cancel': '取消',
      'confirm': '确定',
      'optional': '可选 (Optional)',
      'address_hint': '域名或IP',
      'uuid_hint': '用户 ID (UUID)',
      'password_hint': '密码',
      'edit_node': '编辑节点',
      'add_node': '添加节点',
      'basic_config': '基本配置',
      'protocol': '协议',
      'node_name': '名称',
      'address': '地址',
      'port': '端口',
      'uuid': 'UUID',
      'security_type': '加密方式 (Security)',
      'encryption': '加密 (Encryption)',
      'password': '密码',
      'username': '用户名',
      'method': '加密方法 (Method)',
      'flow': '流控 (Flow)',
      'sni': 'SNI',
      'allow_insecure': '允许不安全连接 (Insecure)',
      'udp_mode': 'UDP 转发模式',
      'private_key': '私钥 (Secret Key)',
      'peer_public_key': '对端公钥 (Peer Public Key)',
      'preshared_key': '预共享密钥 (Pre-shared Key)',
      'local_address': '本地地址',
      'mtu': 'MTU',
      'keep_alive_interval': '保活间隔',
      'transport_config': '传输配置',
      'transport_type': '传输方式',
      'header_type': '伪装类型 (Header Type)',
      'host': '伪装域名 (Host)',
      'path': '路径 (Path)',
      'service_name': '服务名称',
      'grpc_mode': 'gRPC 模式',
      'obfs_seed': '混淆种子 (Finalmask/Seed)',
      'security_config': '安全配置',
      'stream_security': '底层传输安全 (Security)',
      'fingerprint': '指纹 (Fingerprint)',
      'alpn_comma': 'ALPN (以逗号分隔)',
      'reality_public_key': 'Reality Public Key',
      'reality_short_id': 'Reality Short ID',
      'spider_x': 'SpiderX',
      'mux_config': 'Mux 配置',
      'enable_mux': '启用 Mux',
      'concurrency': '并发数 (Concurrency)',
      'save': '保存',
      'tun_service_mode': 'TUN 服务模式',
      'tun_mode_desc': '虚拟网卡接管系统级流量 (需管理员权限)',
      'tun_need_admin': '需要管理员权限才能开启 TUN 模式',
      'tun_uac_prompt': '开启 TUN 模式需要管理员权限，请在弹出的 UAC 窗口中点击"是"。',
      'tun_auto_reset': '已自动重置 TUN 模式开关',
      'socks_port_occupied': 'SOCKS 端口 {port} 已被占用，请关闭占用该端口的程序或更换端口',
      'http_port_occupied': 'HTTP 端口 {port} 已被占用，请关闭占用该端口的程序或更换端口',
      'import_nodes': '导入节点',
      'import_from_clipboard': '从剪贴板导入',
      'import_from_file': '从文件导入',
      'import_nodes_hint': '点击右上角按钮导入节点或订阅',
      'scan_qr_import': '扫描二维码导入节点',
      'import_from_clipboard_success': '成功从剪贴板导入 {count} 个节点',
      'import_from_file_success': '成功从文件导入 {count} 个节点',
      'sub_already_exists': '该订阅链接已存在',
      'sub_auto_added': '检测到订阅链接，已自动添加到“订阅管理”',
      'no_valid_nodes_found': '剪贴板中未发现有效节点或订阅内容',
      'import_failed': '导入失败',
      'import_nodes_hint': '点击右上角按钮导入节点或订阅',
      'batch_node_latency': '批量节点测延迟',
      'tcp_ping_fast': 'TCP Ping (快速测试)',
      'test_conn_speed': '测试服务器连接性，速度快',
      'real_conn_latency': '真实连接 (延迟测试)',
      'simulate_web_access': '模拟真实网页访问，结果准确',
      'test_conn_speed_desc': '测试服务器连接性，速度快，不消耗流量',
      'simulate_web_access_desc': '模拟真实网页访问，结果准确，会消耗少量流量',
      'clear_timeout_nodes': '清除超时节点',
      'latency_timeout': '超时',
      'system_resumed_from_sleep': '[System] 从休眠唤醒，正在重启内核...',
      'got_it': '了解',
      'keep_alive_guide': '持续运行指南',
      'keep_alive_guide_desc': '为了确保代理服务在后台稳定运行，请确保完成以下设置：',
      'keep_alive_step1': '1. 允许应用自启动',
      'keep_alive_step2': '2. 关闭电池优化（设为不限制）',
      'keep_alive_step3': '3. 在多任务界面锁定 Lightning',
      'keep_alive_step4': '4. 允许后台常驻运行',
      'redirecting_to_settings': '正在为您跳转到系统设置...',
      'export_config': '备份配置 (导出)',
      'import_config': '恢复配置 (导入)',
      'config_backed_up': '配置已备份至剪贴板',
      'backup_failed': '备份失败: {error}',
      'config_restored': '配置恢复成功，请重启应用生效',
      'import_failed_invalid': '导入失败: 无效的配置格式',
      'restart_required_hint': '\n\n注意：此设置需要重启 VPN 连接后才能生效。',
    },
    'en': {
      'sub_settings': 'Subscriptions',
      'nodes_manage': 'Nodes',
      'advanced_config': 'Advanced',
      'control_panel': 'Dashboard',
      'all_logs': 'All Logs',
      'realtime_logs': 'Real-time Logs',
      'download': 'Download',
      'upload': 'Upload',
      'global_mode': 'Global Mode',
      'rule_mode': 'Rule Mode',
      'direct_mode': 'Direct Mode',
      'logs_copied': 'Logs copied to clipboard',
      'no_logs_found': 'No log records',
      'logs_help_desc':
          'Operational logs will be displayed here after starting the proxy',
      'failure_diagnosis': 'Connection Failure Diagnosis',
      'diagnostic_suggestion':
          '💡 Suggestion: If the above steps do not solve the problem, please try switching to another node or check your network connection.',
      'got_it': 'Got it',
      'app_subtitle': 'The Next Gen Proxy Client',
      'app_version': 'Version 1.0.32 • Build 35',
      'app_status_stable': 'v1.0.0 Stable',
      'realtime_traffic_chart': 'Real-time Traffic Chart',
      'traffic_and_mode': 'Traffic & Mode Control',
      'traffic_and_mode_help':
          'Shows real-time upload/download speeds and total traffic. You can quickly switch between Global, Rule, or Direct modes using the toggles above.',
      'tunnel_details': 'Tunnel Details',
      'tunnel_details_help':
          'Here you can quickly switch the current server node, adjust routing strategies, and toggle Windows system proxy takeover with one click.\n\nTip: Latency test now uses HTTPS true connection handshake, reflecting actual web browsing response speed.',
      'net_recovering': 'Checking network connectivity...',
      'net_recovered': 'Network recovered, attempting auto-reconnect',
      'wintun_missing':
          'Missing core virtual network driver wintun.dll. Please ensure the program directory is complete or reinstall.',
      'file_path': 'File Path',
      'enter_file_path': 'Please enter file path',
      'enter_sub_link': 'Please enter subscription link',
      'invalid_sub_link': 'Please enter a valid http:// or https:// link',
      'auto_reload_file': 'Periodically reload file content',
      'update_interval_hours': 'Update Interval (Hours): ',
      'import_from_clipboard_desc': 'Import copied links or subscriptions',
      'import_from_file_desc': 'Support JSON or link list files',
      'no_nodes_found': 'No nodes available',
      'edit_node_label': 'Edit Node',
      'test_latency': 'Test Latency',
      'copy_link_label': 'Copy Link',
      'share_qr': 'QR Code Share',
      'export_config_label': 'Export Full Config',
      'physical_destroy': 'Physical Destroy',
      'link_copied_success': 'Link copied to clipboard',
      'confirm_delete': 'Confirm Delete',
      'delete_node_confirm': 'Are you sure you want to delete node "{name}"?',
      'multi_select': 'Multi-select Mode',
      'delete_node_label': 'Delete Node',
      'batch_export_success':
          'Successfully exported {count} nodes to clipboard',
      'close': 'Close',
      'manual_add_ss': 'Manual add Shadowsocks',
      'strong_deduplicate': 'Force Deduplicate Nodes',
      'nodes_cleanup': 'Nodes Cleanup',
      'clear_timeout': 'Clear Timeout Nodes',
      'clear_timeout_success': 'Successfully cleared {count} timeout nodes',
      'deduplicate_success': 'Successfully merged {count} duplicate nodes',
      'test_group_latency': 'Test Group Latency',
      'test_all_speed': 'Test All Speed',
      'search_nodes': 'Search nodes...',
      'selected_count': 'Selected {count}',
      'stop_speed_test': 'Stop speed test',
      'import_clipboard': 'Import from clipboard',
      'import_from_file': 'Import from file',
      'sort_latency': 'Sort by Latency',
      'sort_name': 'Sort by Name',
      'manual_add_vmess': 'Manual add VMess',
      'manual_add_vless': 'Manual add VLESS',
      'manual_add_trojan': 'Manual add Trojan',
      'manual_add_shadowsocks': 'Manual add Shadowsocks',
      'manual_add_socks': 'Manual add SOCKS',
      'manual_add_hysteria2': 'Manual add Hysteria2',
      'manual_add_tuic': 'Manual add TUIC',
      'manual_add_wireguard': 'Manual add WireGuard',
      'auto_deduplicate': 'Auto Deduplicate',
      'auto_select_best': 'Auto Select Best',
      'auto_selecting': 'Auto selecting best node...',
      'auto_select_done': 'Switched to the fastest node',
      'auto_select_failed': 'Auto select failed, please check network',
      'speed_test_progress': 'Speed Test Progress',
      'nodes_count': '{count} nodes',
      'manual_import': 'Manual Import',
      'nodes_manage': 'Nodes',
      'sub_update_failed': 'Subscription "{name}" update failed: {error}',
      'sub_update_success': 'Subscription "{name}" update success',
      'update_all': 'Update all',
      'manual_input': 'Manual input',
      'no_subs_found': 'No subscriptions found',
      'click_add_sub':
          'Click the button in the top right to add a subscription',
      'clipboard_empty': 'Clipboard is empty',
      'no_valid_sub_link':
          'No valid subscription link in clipboard (must start with http)',
      'edit_sub_label': 'Edit Subscription',
      'close_auto_update': 'Disable Auto Update',
      'open_auto_update': 'Enable Auto Update',
      'copy_sub_link': 'Copy Subscription Link',
      'sub_link_copied': 'Subscription link copied to clipboard',
      'delete_sub_label': 'Delete Subscription',
      'enter_sub_name_hint': 'Please enter subscription name',
      'delete_sub_confirm':
          'Are you sure you want to delete subscription "{name}"? Related nodes will also be removed.',
      'enter_at_least_one': 'Please fill in at least one filter condition',
      'operation_failed_need_admin':
          'Operation failed, may need administrator privileges',
      'search_apps_hint': 'Search app name...',
      'exempt_all': 'Exempt All',
      'clear_all': 'Clear All',
      'scanned_apps_count': 'Scanned {count} apps',
      'no_apps_found': 'No matching apps found',
      'uwp_exemption_warning':
          'Note: After modifying the exemption list, related apps may need to be restarted to take effect.',
      'remote_dns_preset': 'Remote DNS Presets',
      'domestic_dns_preset': 'Domestic DNS Presets',
      'fake_dns': 'Fake DNS',
      'enable_fake_dns': 'Enable Fake DNS',
      'fake_dns_desc':
          'Significantly improve domain resolution speed and reduce latency',
      'remote_dns_desc':
          'Encrypted DNS (DoH/DoT) recommended to prevent pollution',
      'enable_ipv6': 'Enable IPv6',
      'enable_ipv6_desc': 'Whether to resolve and return IPv6 addresses',
      'domestic_dns': 'Domestic DNS',
      'domestic_dns_desc': 'Domain resolution for direct traffic',
      'local_dns': 'Local DNS Service',
      'enable_local_dns': 'Enable Local DNS',
      'enable_local_dns_desc': 'Establish local DNS listening service',
      'local_dns_port': 'Listening Port',
      'local_dns_port_desc': 'Default 10853',
      'dns_hosts': 'DNS Static Mapping (Hosts)',
      'dns_hosts_desc': 'Custom static mapping of domains to IPs',
      'preset': 'Presets',
      'connecting_to_network': 'Connecting to network...',
      'encrypting_tunnel': 'Encrypting VPN tunnel...',
      'vpn_running': 'VPN Service Running',
      'vpn_stopped': 'Service Stopped',
      'vpn_connected_success': 'Encrypted tunnel connected successfully',
      'initializing_protocol': 'Initializing encryption protocol...',
      'click_switch_to_start': 'Click switch to start proxy',
      'select_node_first': 'Please select a node first',
      'duration': 'Duration',
      'protocol': 'Protocol',
      'unknown': 'Unknown',
      'status': 'Status',
      'stable': 'Stable',
      'standby': 'Standby',
      'no_node_selected': 'No node selected',
      'click_to_change_routing': 'Click to change routing strategy',
      'connection_failed': 'Connection Failed',
      'connection_failed_desc':
          'Node connection failed, possibly due to incompatible configuration or node expiration. Please try another node.',
      'hide_details': 'Hide Details',
      'view_error_details': 'View Error Details',
      'error_log_copied': 'Error log copied to clipboard',
      'copy_log': 'Copy Log',
      'kernel_start_failed': 'Core start failed: {error}',
      'port_in_use':
          'Port in use: Local port needed by Lightning (e.g., 10808) is already occupied by another program. Please check if other proxy software (like Clash, v2rayN, etc.) is running, and try again after closing them.',
      'tun_elevation_failed':
          'Insufficient privileges: TUN virtual network card mode requires administrator privileges. Please right-click the Lightning shortcut and select "Run as administrator".',
      'start_timeout':
          'Start timeout: Core response timeout. Please check if the node configuration is valid or restart the software.',
      'show_main_window': 'Show Main Window',
      'take_over_system_proxy': 'System Proxy',
      'routing_mode': 'Routing Mode',
      'mode_rule_label': 'Rule Mode',
      'mode_global_label': 'Global Mode',
      'mode_direct_label': 'Direct Mode',
      'disconnect_vpn': 'Disconnect',
      'connect_vpn': 'Connect',
      'exit_app': 'Exit',
      'more_actions': 'More Actions',
      'switching_node': 'Switching node...',
      'stopping_vpn': 'Stopping VPN...',
      'auto_reset_tun': 'Auto reset TUN mode switch',
      'preparing_resources': 'Preparing resource files...',
      'submitting_config':
          'Submitting configuration to kernel and requesting VPN permissions...',
      'net_disconnected': '[Connectivity] Network disconnected',
      'sub_sync_start':
          'Subscription [{name}] reached update interval, starting auto-sync...',
      'mode_changed_restarting':
          'Mode change detected, updating kernel configuration...',
      'rules_changed_restarting':
          'Routing rules change detected, updating kernel configuration...',
      'auto_reconnect_triggered': '[Tracer] ⚠️ Auto-reconnect triggered',
      'high_freq_jitter_blocked':
          '[Tracer] 🛡️ High-frequency network jitter intercepted, skipping this reconnect',
      'duplicate_restart_ignored':
          '[Restart] Duplicate restart request detected, ignored',
      'vpn_disconnected_by_cleanup':
          '[Tracer] 🔌 VPN state modified to disconnected, trigger: Pre-reconnect cleanup',
      'vpn_disconnected_by_user':
          '[Tracer] 🔌 VPN state modified to disconnected, trigger: User manual stop',
      'vpn_disconnected_by_kernel':
          '[Tracer] 🔌 VPN state modified to disconnected, trigger: Abnormal termination or kernel exit',
      'vpn_connected_success_log': '[Flutter] VPN connected successfully!',
      'vpn_disconnected_log': '[Flutter] VPN disconnected',
      'kernel_error_log': '[Flutter] Kernel error: {error}',
      'preparing_node_log': 'Preparing to connect to node: {name}',
      'start_vpn_failed_log': 'Start VPN failed: {error}',
      'stop_vpn_failed_log': 'Disconnect VPN failed: {error}',
      'driver_missing_error':
          '🛡️ Driver Missing: Missing core virtual network driver wintun.dll. Please ensure the program directory is complete or run the software as administrator.',
      'tun_components_lost':
          'Detected missing TUN mode core components, unable to start encrypted tunnel.',
      'tray_tooltip_connected': 'Lightning VPN (Connected)',
      'tray_tooltip_disconnected': 'Lightning VPN',
      'tray_tooltip_connecting': 'Lightning VPN (Connecting...)',
      'confirm_sub_info': 'Confirm Subscription Info',
      'add_subscription': 'Add subscription',
      'sub_name': 'Subscription name',
      'give_sub_name': 'Give the subscription a name',
      'enter_sub_name': 'Please enter subscription name',
      'auto_update': 'Auto update',
      'sync_cloud_nodes': 'Regularly sync cloud nodes',
      'routing_rules': 'Routing Rules',
      'no_custom_rules': 'No custom rules',
      'click_add_rule':
          'Click the button in the top right to add a routing rule',
      'rule_options': 'Rule options',
      'delete_rule': 'Delete rule',
      'add_rule': 'Add rule',
      'domain_comma': 'Domain (comma separated)',
      'domain_label': 'Domain',
      'ip_comma': 'IP (comma separated)',
      'ip_label': 'IP',
      'port_comma': 'Port (comma separated)',
      'port_label': 'Port',
      'protocol_comma': 'Protocol (comma separated)',
      'protocol_label': 'Protocol',
      'network_label': 'Network',
      'action': 'Action',
      'direct_action': 'Direct',
      'proxy_action': 'Proxy',
      'block_action': 'Block',
      'enter_at_least_one': 'Please enter at least one filter condition',
      'app_split': 'App Split',
      'bypass_apps_desc': 'Bypass selected apps (Blacklist)',
      'proxy_apps_desc': 'Proxy selected apps (Whitelist)',
      'search_installed_apps': 'Search installed apps...',
      'kernel_info': 'Kernel Info',
      'kernel_info_help':
          'Function: Display the information of the core proxy engine.\n\nDetails: Lightning uses Xray-core, a high-performance and feature-rich network proxy core.',
      'log_level': 'Log Level',
      'log_level_help':
          'Function: Control the verbosity of logs generated by the proxy core.\n\nOn: Higher levels (DEBUG/INFO) provide more details for troubleshooting but may use more resources. ERROR/NONE minimize logs.\n\nNote: This setting requires a VPN restart to take effect.',
      'mux_title': 'Mux Multiplexing',
      'mux_desc':
          'Multiplex multiple data streams over a single TCP connection to reduce latency.',
      'mux_enabled_help':
          'Function: Multiplex multiple data streams over a single TCP connection.\n\nOn: Significantly reduces TCP handshake latency when accessing many small files (like web browsing), improving responsiveness.\n\nOff: More stable for large file downloads and may have higher bandwidth limits on some ISP networks.\n\nNote: This setting requires a VPN restart to take effect.',
      'fragment_title': 'Enable Fragment (Anti-SNI Blocking)',
      'fragment_desc':
          'Split TLS handshake packets to bypass SNI-based domain blocking.',
      'fragment_help':
          'Fragment mode can significantly improve connectivity in strict network environments, especially when dealing with precise blocking of specific domains in certain regions.\n\nNote: This setting requires a VPN restart to take effect.',
      'system_proxy_title': 'Auto Enable System Proxy',
      'system_proxy_desc':
          'Automatically modify Windows registry to hijack traffic after core starts.',
      'system_proxy_help':
          'Function: Automatically configure the Windows system proxy settings.\n\nOn: Most browser and system traffic will automatically go through the proxy without manual configuration.\n\nOff: You need to manually set proxy settings in each application.',
      'sniffing_title': 'Traffic Sniffing',
      'sniffing_desc':
          'Identify real domains in encrypted traffic for more accurate routing.',
      'sniffing_help':
          'Traffic sniffing extracts the target domain from TLS/HTTP handshake packets. This is very effective for handling IP-based rules or bypassing DNS pollution.',
      'domain_strategy_title': 'Domain Strategy',
      'domain_strategy_help':
          'AsIs: Use domain name directly, resolved by server.\n\nIPIfNonMatch: If no rule matches the domain, resolve to IP and match again.\n\nIPOnDemand: Resolve domain name immediately if an IP-based rule matches.',
      'tun_stack_title': 'TUN Stack',
      'tun_stack_help':
          'gVisor: User-space stack, best compatibility and safest, recommended.\n\nSystem: Use Windows system stack, higher performance but unstable in some environments.\n\nMixed: Mixed mode.',
      'clean_proxy_on_exit_title': 'Clean Proxy on Exit',
      'clean_proxy_on_exit_desc':
          'Automatically restore Windows proxy settings on exit.',
      'clean_proxy_on_exit_help':
          'When enabled, the system will automatically clean up proxy configurations in the registry when you exit Lightning, preventing internet access issues.',
      'hide_to_tray_title': 'Hide to Tray',
      'hide_to_tray_desc': 'Hide to system tray when closing window',
      'hide_to_tray_help':
          'Function: Keep the program running in the background when the main window is closed.\n\nYou can restore the window or exit the program via the system tray icon.',
      'rules_manage': 'Rules Management',
      'rules_db_manage': 'GeoData Management',
      'sync_geodata': 'Sync GeoData (geoip/geosite)',
      'sync_geodata_desc': 'Sync latest geoip.dat and geosite.dat from GitHub',
      'updating_geodata': 'Downloading: {progress}%',
      'update_geodata_success': '✨ GeoData updated successfully',
      'update_geodata_failed': '❌ Update failed: {error}',
      'disconnect_before_update':
          '⚠️ Please disconnect VPN before updating GeoData',
      'ui_display': 'UI Display',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'language': 'Language',
      'conn_automation': 'Automation',
      'uwp_exemption_title': 'UWP Loopback Exemption',
      'uwp_exemption_desc': 'Fix connection issues for Windows Store apps',
      'inbound_ports_title': 'Inbound Ports',
      'inbound_ports_desc': 'Socks: {socks} | HTTP: {http}',
      'backup_restore_desc': 'Backup or restore configurations',
      'rules_manage_desc': 'Manage custom routing rules',
      'bypass_local_desc': 'Bypass local network addresses',
      'allow_lan_desc': 'Allow other devices in LAN to use proxy',
      'current_mode': 'Current Mode',
      'app_split_desc': 'Select which apps to proxy or bypass',
      'rules_manage_help':
          'Function: Manage custom routing rules for domains and IP addresses.\n\nYou can define which traffic should go through the proxy, connect directly, or be blocked.',
      'uwp_exemption_help':
          'Function: Fix the issue where Windows UWP applications (like Microsoft Store, Edge, etc.) cannot access the network via local proxy due to "Loopback" restrictions.',
      'dns_settings_help':
          'Function: Configure DNS resolution strategies and servers.\n\nIncludes Remote DNS for overseas, Domestic DNS for local, and Fake DNS for anti-pollution.\n\nNote: This setting requires a VPN restart to take effect.',
      'backup_restore': 'Backup & Restore',
      'backup_restore_help':
          'Function: Export your current nodes and settings to the clipboard, or restore them from a previously exported backup string.',
      'about': 'About',
      'about_desc': 'View software info',
      'about_help':
          'Lightning is a high-performance network proxy client. This page displays software version, core information, and developer details.',
      'dns_settings': 'DNS Settings',
      'routing_strategy': 'Routing Strategy',
      'routing_strategy_help':
          'Global Mode: All network requests go through the proxy. Suitable for scenarios where you need to hide your IP at all times, but domestic websites may be slower.\n\nRule Mode: Intelligently decides based on rule lists. Domestic sites connect directly, while overseas sites use the proxy. Recommended.\n\nDirect Mode: Do not use a proxy; connect directly to the internet.\n\nNote: This setting requires a VPN restart to take effect.',
      'bypass_local': 'Bypass Local',
      'bypass_local_help':
          'Function: Identify local network addresses like 192.168.x.x.\n\nOn: Access local devices (routers, NAS, printers) directly without going through the proxy, ensuring the fastest speed and normal local access.\n\nOff: Local traffic may be redirected to the proxy server, potentially causing issues accessing local devices.\n\nNote: This setting requires a VPN restart to take effect.',
      'tcp_congestion': 'TCP Congestion',
      'tcp_congestion_help':
          'BBR: Google\'s congestion control algorithm. Especially effective for high-latency, high-loss cross-border networks to maximize bandwidth.\n\nCubic/Reno: Classic TCP algorithms with good compatibility, performing well on stable networks with low packet loss.\n\nNote: This setting requires a VPN restart to take effect.',
      'allow_lan': 'Allow LAN Connection',
      'allow_lan_help':
          'Function: Share this PC\'s proxy connection with other devices (phones, consoles, other PCs) on the same local network.\n\nUsage Guide:\n1. Ensure Windows Firewall allows Lightning and devices are on the same network.\n2. Note this PC\'s LAN IP ({ip}) and HTTP proxy port ({port}).\n3. Manually configure proxy settings on the other device:\n   - Server/Hostname: {ip}\n   - Port: {port}\n\nNote: This PC will act as a proxy gateway. Requires a VPN restart to take effect.',
      'lan_ip_title': 'LAN IP Address',
      'lan_port_title': 'Proxy Port',
      'copy_address': 'Copy Address',
      'inbound_ports_help':
          'Function: Set the local ports for Socks5 and HTTP proxy services.\n\nOn: Other apps on this device or other devices in the LAN can manually use these ports to connect to the proxy.\n\nOff: No local ports will be opened, and manual proxy configuration will not be possible.\n\nNote: This setting requires a VPN restart to take effect.',
      'auto_start_help': 'Automatically run Lightning at startup',
      'auto_start_tip':
          'Function: When enabled, Lightning will load automatically when Windows starts.\n\nWorks best with "Silent Startup".',
      'sync_geodata_help':
          'Function: Update routing databases (geoip.dat / geosite.dat) from official sources.\n\nNote: VPN must be disconnected to update GeoData.',
      'tun_mode_help':
          'Function: Take over system-wide traffic via virtual network card (Wintun).\n\nOn: All software (including those without proxy settings) will automatically go through the proxy.\n\nRequirements: Administrator privileges and Wintun driver installation.',
      'appearance_help':
          'Function: Toggle application theme (Light or Dark mode).',
      'language_help':
          'Function: Switch the interface language (Chinese or English).',
      'auto_start': 'Auto Start',
      'auto_start_help': 'Automatically run Lightning at startup',
      'keep_alive': 'Keep Alive',
      'keep_alive_help':
          'Function: Prevent the system from killing the background process.',
      'auto_reconnect': 'Auto Reconnect',
      'auto_reconnect_help':
          'Automatically attempt to reconnect when the network is interrupted or switched.',
      'hotkey_title': 'Main Window Hotkey',
      'hotkey_help':
          'Function: Set a global shortcut to quickly wake or hide the Lightning main window anytime.\n\nFormat: Supports combinations like Alt, Ctrl, Shift with letters (e.g., Alt+Q).',
      'hotkey_input_label': 'Key Combination',
      'hotkey_format_hint': 'Example: Alt+Q, Ctrl+Shift+S',
      'show_traffic': 'Show Traffic',
      'show_traffic_help':
          'Function: Show real-time upload and download speeds in the status bar or floating window.',
      'route_splitting': 'Routing & Splitting',
      'protocol_kernel': 'Protocol & Kernel',
      'adv_network': 'Advanced Network',
      'remote_dns': 'Remote DNS',
      'about_title': 'About Lightning',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'optional': 'Optional',
      'address_hint': 'Domain or IP',
      'uuid_hint': 'User ID (UUID)',
      'password_hint': 'Password',
      'edit_node': 'Edit Node',
      'add_node': 'Add Node',
      'basic_config': 'Basic Configuration',
      'protocol': 'Protocol',
      'node_name': 'Name',
      'address': 'Address',
      'port': 'Port',
      'uuid': 'UUID',
      'security_type': 'Security Type',
      'encryption': 'Encryption',
      'password': 'Password',
      'username': 'Username',
      'method': 'Method',
      'flow': 'Flow',
      'sni': 'SNI',
      'allow_insecure': 'Allow Insecure',
      'udp_mode': 'UDP Mode',
      'private_key': 'Private Key',
      'peer_public_key': 'Peer Public Key',
      'preshared_key': 'Pre-shared Key',
      'local_address': 'Local Address',
      'mtu': 'MTU',
      'keep_alive_interval': 'Keep-alive Interval',
      'transport_config': 'Transport Configuration',
      'transport_type': 'Transport Type',
      'header_type': 'Header Type',
      'host': 'Host',
      'path': 'Path',
      'service_name': 'Service Name',
      'grpc_mode': 'gRPC Mode',
      'obfs_seed': 'Obfuscation Seed',
      'security_config': 'Security Configuration',
      'stream_security': 'Stream Security',
      'fingerprint': 'Fingerprint',
      'alpn_comma': 'ALPN (comma separated)',
      'reality_public_key': 'Reality Public Key',
      'reality_short_id': 'Reality Short ID',
      'spider_x': 'SpiderX',
      'mux_config': 'Mux Configuration',
      'enable_mux': 'Enable Mux',
      'concurrency': 'Concurrency',
      'save': 'Save',
      'tun_service_mode': 'TUN Service Mode',
      'tun_mode_desc':
          'Virtual network card takes over system-level traffic (Admin required)',
      'tun_need_admin': 'Admin privileges are required to enable TUN mode',
      'tun_uac_prompt':
          'Enabling TUN mode requires admin privileges, please click "Yes" in the popup UAC window.',
      'tun_auto_reset': 'TUN mode switch has been automatically reset',
      'socks_port_occupied':
          'SOCKS port {port} is occupied, please close the program using this port or change the port',
      'http_port_occupied':
          'HTTP port {port} is occupied, please close the program using this port or change the port',
      'import_nodes': 'Import Nodes',
      'import_from_clipboard': 'Import from Clipboard',
      'import_from_file': 'Import from File',
      'import_nodes_hint':
          'Click the button in the top right to import nodes or subscriptions',
      'scan_qr_import': 'Scan QR Code to Import Node',
      'import_from_clipboard_success':
          'Successfully imported {count} nodes from clipboard',
      'import_from_file_success':
          'Successfully imported {count} nodes from file',
      'sub_already_exists': 'Subscription already exists',
      'sub_auto_added':
          'Subscription link detected and added to Subscription Management',
      'no_valid_nodes_found': 'No valid nodes or subscriptions found',
      'import_failed': 'Import failed',
      'batch_node_latency': 'Batch Node Latency',
      'tcp_ping_fast': 'TCP Ping (Fast)',
      'test_conn_speed': 'Test server connectivity, fast',
      'real_conn_latency': 'Real Connection (Latency)',
      'simulate_web_access': 'Simulate real web access, accurate',
      'test_conn_speed_desc':
          'Test server connectivity, fast, no traffic consumption',
      'simulate_web_access_desc':
          'Simulate real web access, accurate, small traffic consumption',
      'clear_timeout_nodes': 'Clear Timeout Nodes',
      'latency_timeout': 'Timeout',
      'system_resumed_from_sleep':
          '[System] Resumed from sleep, restarting kernel...',
      'got_it': 'Got it',
      'keep_alive_guide': 'Keep-alive Guide',
      'keep_alive_guide_desc':
          'To ensure the proxy service runs stably in the background, please make sure to complete the following settings:',
      'keep_alive_step1': '1. Allow app auto-start',
      'keep_alive_step2':
          '2. Disable battery optimization (set to Unrestricted)',
      'keep_alive_step3': '3. Lock Lightning in multi-task interface',
      'keep_alive_step4': '4. Allow background running',
      'redirecting_to_settings': 'Redirecting to system settings...',
      'export_config': 'Export Config (Backup)',
      'import_config': 'Import Config (Restore)',
      'config_backed_up': 'Config backed up to clipboard',
      'backup_failed': 'Backup failed: {error}',
      'config_restored':
          'Config restored successfully, please restart the app to take effect',
      'import_failed_invalid': 'Import failed: Invalid config format',
      'restart_required_hint':
          '\n\nNote: This setting requires a VPN restart to take effect.',
      'app_status_stable': 'v1.0.0 Stable',
      'traffic_and_mode': 'Traffic & Mode Control',
      'tunnel_details': 'Tunnel Details',
      'wintun_missing':
          'Missing core virtual network driver wintun.dll. Please ensure the program directory is complete or reinstall.',
      'file_path': 'File Path',
      'enter_file_path': 'Please enter file path',
      'enter_sub_link': 'Please enter subscription link',
      'invalid_sub_link': 'Please enter a valid http:// or https:// link',
      'auto_reload_file': 'Periodically reload file content',
      'update_interval_hours': 'Update Interval (Hours): ',
      'edit_sub_label': 'Edit Subscription',
      'close_auto_update': 'Disable Auto Update',
      'open_auto_update': 'Enable Auto Update',
      'copy_sub_link': 'Copy Subscription Link',
      'sub_link_copied': 'Subscription link copied to clipboard',
      'delete_sub_label': 'Delete Subscription',
      'enter_sub_name_hint': 'Please enter subscription name',
      'delete_sub_confirm':
          'Are you sure you want to delete subscription "{name}"? Related nodes will also be removed.',
      'enter_at_least_one': 'Please fill in at least one filter condition',
      'operation_failed_need_admin':
          'Operation failed, may need administrator privileges',
      'search_apps_hint': 'Search app name...',
      'exempt_all': 'Exempt All',
      'clear_all': 'Clear All',
      'scanned_apps_count': 'Scanned {count} apps',
      'no_apps_found': 'No matching apps found',
      'uwp_exemption_warning':
          'Note: After modifying the exemption list, related apps may need to be restarted to take effect.',
      'remote_dns_preset': 'Remote DNS Presets',
      'domestic_dns_preset': 'Domestic DNS Presets',
      'fake_dns': 'Fake DNS',
      'enable_fake_dns': 'Enable Fake DNS',
      'fake_dns_desc':
          'Significantly improve domain resolution speed and reduce latency',
      'remote_dns_desc':
          'Encrypted DNS (DoH/DoT) recommended to prevent pollution',
      'enable_ipv6': 'Enable IPv6',
      'enable_ipv6_desc': 'Whether to resolve and return IPv6 addresses',
      'domestic_dns': 'Domestic DNS',
      'domestic_dns_desc': 'Domain resolution for direct traffic',
      'local_dns': 'Local DNS Service',
      'enable_local_dns': 'Enable Local DNS',
      'enable_local_dns_desc': 'Establish local DNS listening service',
      'local_dns_port': 'Listening Port',
      'local_dns_port_desc': 'Default 10853',
      'dns_hosts': 'DNS Static Mapping (Hosts)',
      'dns_hosts_desc': 'Custom static mapping of domains to IPs',
      'preset': 'Presets',
    },
  };

  String get(String key, {Map<String, dynamic>? args}) {
    // 优先从当前语言包找
    String? value = _localizedValues[locale.languageCode]?[key];

    // 如果当前是英文且没找到，尝试从中文包找（作为回退）
    if (value == null && locale.languageCode != 'zh') {
      value = _localizedValues['zh']?[key];
    }

    // 如果还是没找到，直接显示 key（通常是英文标识符）
    value ??= key;

    if (args != null) {
      args.forEach((key, val) {
        value = value!.replaceAll('{$key}', val.toString());
      });
    }
    return value!;
  }

  static S of(BuildContext context, [WidgetRef? ref]) {
    // Force reactive update if ref is provided
    if (ref != null) {
      final locale = ref.watch(localizationProvider);
      return S(locale);
    }
    return Localizations.of<S>(context, S) ?? S(const Locale('zh', 'CN'));
  }
}

class _SDelegate extends LocalizationsDelegate<S> {
  const _SDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'zh'].contains(locale.languageCode);

  @override
  Future<S> load(Locale locale) => SynchronousFuture<S>(S(locale));

  @override
  bool shouldReload(_SDelegate old) => false;
}
